const words = [
  { word: "agree (with)", translation: "rozilik bildirmoq (bilan)" },
  { word: "alone", translation: "yolg'iz" },
  { word: "astronaut", translation: "kosmonavt" },
  { word: "beach", translation: "plyaj" },
  { word: "dangerous", translation: "xavfli" },
  { word: "discount", translation: "chegirma" },
  { word: "lazy", translation: "dangasa" },
  { word: "library", translation: "kutubxona" },
  { word: "museum", translation: "muzey" },
  { word: "scientist", translation: "olim" },
  { word: "opal", translation: "opal (qimmatbaho tosh)" },
  { word: "opposite", translation: "qarama-qarshi" },
  { word: "organized", translation: "tartibli" },
  { word: "palace", translation: "saroy" },
  { word: "passport", translation: "pasport" },
  { word: "seal", translation: "muhr; tyulen" },
  { word: "shop", translation: "do'kon" },
  { word: "shower", translation: "dush" },
  { word: "sickness", translation: "kasallik" },
  { word: "sleeping bag", translation: "uxlab yotish uchun xalta (spalnik)" },
  { word: "soup", translation: "sho'rva" },
  { word: "space", translation: "fazo" },
  { word: "spacesuit", translation: "kosmonavt kiyimi" },
  { word: "start", translation: "boshlamoq" },
  { word: "stop", translation: "to'xtamoq" },
  { word: "student card", translation: "talabalar guvohnomasi" },
  { word: "think (about)", translation: "o'ylamoq (haqida)" },
  { word: "tired", translation: "charchagan" },
  { word: "title", translation: "nom, sarlavha" },
  { word: "toast", translation: "qovurilgan non (tost)" },
  { word: "trainee", translation: "stajyor" },
  { word: "volcano", translation: "vulqon" },
  { word: "wait", translation: "kutmoq" },
  { word: "wake up", translation: "uyg'onmoq" },
  { word: "wall", translation: "devor" },
  { word: "watch a film", translation: "film tomosha qilmoq" },
  { word: "watch TV", translation: "televizor ko'rmoq" },
  { word: "work", translation: "ishlamoq" },
  { word: "zoology", translation: "zoologiya" },
  { word: "address", translation: "manzil" },
  { word: "administrator", translation: "administrator" },
  { word: "again", translation: "yana" },
  { word: "airline", translation: "aviakompaniya" },
  { word: "answer", translation: "javob" },
  { word: "author", translation: "muallif" },
  { word: "baker", translation: "novvoy" },
  { word: "beginner", translation: "boshlovchi, yangi o'rganuvchi" },
  { word: "builder", translation: "quruvchi" },
  { word: "bus driver", translation: "avtobus haydovchisi" },
  { word: "businessman", translation: "biznesmen" },
  { word: "businesswoman", translation: "biznes ayol" },
  { word: "calm", translation: "xotirjam, tinch" },
  { word: "chef", translation: "oshpaz" },
  { word: "cleaner", translation: "tozalovchi" },
  { word: "clever", translation: "aqlli" },
  { word: "colleague", translation: "hamkasb" },
  { word: "company", translation: "kompaniya" },
  { word: "dancer", translation: "raqqosa yoki raqqos" },
  { word: "dentist", translation: "tish shifokori" },
  { word: "driver", translation: "haydovchi" },
  { word: "earn", translation: "daromad qilmoq" },
  { word: "factory", translation: "zavod" },
  { word: "farmer", translation: "fermer" },
  { word: "fix", translation: "tuzatmoq" },
  { word: "forest", translation: "o'rmon" },
  { word: "forget", translation: "unutmoq" },
  { word: "hairdresser", translation: "sartarosh" },
  { word: "important", translation: "muhim" },
  { word: "inside", translation: "ichkarida" },
  { word: "internet", translation: "internet" },
  { word: "journalist", translation: "jurnalist" },
  { word: "later", translation: "keyinroq" },
  { word: "lonely", translation: "yolg'iz" },
  { word: "lookout", translation: "kuzatuvchi yoki qarovchi" },
  { word: "lucky", translation: "omadli" },
  { word: "magazine", translation: "jurnal" },
  { word: "manager", translation: "menejer" },
  { word: "money", translation: "pul" },
  { word: "MP3 player", translation: "MP3 pleer" },
  { word: "musician", translation: "musiqachi" },
  { word: "nurse", translation: "hamshira" },
  { word: "office worker", translation: "ofis xodimi" },
  { word: "painter", translation: "rassom" },
  { word: "part-time", translation: "yarim kunlik" },
  { word: "photographer", translation: "fotograf" },
  { word: "piano", translation: "pianino" },
  { word: "pilot", translation: "uchuvchi" },
  { word: "place of work", translation: "ish joyi" },
  { word: "police officer", translation: "politsiya xodimi" },
  { word: "retired", translation: "nafaqadagi" },
  { word: "salary", translation: "ish haqi" },
  { word: "silent", translation: "jim, sokin" },
  { word: "singer", translation: "qo'shiqchi" },
  { word: "student", translation: "talaba" },
  { word: "teacher", translation: "o'qituvchi" },
  { word: "ticket", translation: "chipta" },
  { word: "tower", translation: "minor" },
  { word: "uniform", translation: "forma" },
  { word: "unusual", translation: "noodatiy" },
  { word: "well-paid", translation: "yaxshi to'lanadigan" },
  { word: "winner", translation: "g'olib" },
  {
    word: "work freelance",
    translation: "mustaqil ishlamoq (freelancer bo'lish)",
  },
  { word: "work long hours", translation: "uzoq vaqt ishlamoq" },
  { word: "writer", translation: "yozuvchi" },
  { word: "above", translation: "ustida, yuqorida" },
  { word: "airport", translation: "aeroport" },
  { word: "armchair", translation: "qo‘ltiqli stul" },
  { word: "bank", translation: "bank" },
  { word: "bathroom", translation: "hammom" },
  { word: "bed", translation: "karavot" },
  { word: "bedroom", translation: "yotoqxona" },
  { word: "behind", translation: "orqasida" },
  { word: "between", translation: "o‘rtasida" },
  { word: "big", translation: "katta" },
  { word: "booking form", translation: "bron qilish shakli" },
  { word: "bookshop", translation: "kitob do‘koni" },
  { word: "building", translation: "bino" },
  { word: "campsite", translation: "lager joyi (kamp uchun joy)" },
  { word: "capital", translation: "poytaxt" },
  { word: "carpet", translation: "gilam" },
  { word: "cheap", translation: "arzon" },
  { word: "chemist", translation: "dorixona; kimyogar" },
  { word: "cinema", translation: "kino teatr" },
  { word: "clean", translation: "toza" },
  { word: "cooker", translation: "oshxona plitasi" },
  { word: "dining room", translation: "ovqatlanish xonasi" },
  { word: "dishwasher", translation: "idish yuvish mashinasi" },
  { word: "easy", translation: "oson" },
  { word: "expensive", translation: "qimmat" },
  { word: "fantastic", translation: "ajoyib" },
  { word: "flat", translation: "kvartira" },
  { word: "fridge", translation: "muzlatgich" },
  { word: "furniture", translation: "mebel" },
  { word: "garage", translation: "garaj" },
  { word: "hairdresser's", translation: "sartaroshxona" },
  { word: "hospital", translation: "shifoxona" },
  { word: "housemate", translation: "uy sherigi" },
  { word: "in front of", translation: "oldida" },
  { word: "instructions", translation: "ko‘rsatmalar" },
  { word: "kitchen", translation: "oshxona" },
  { word: "launderette", translation: "kir yuvish joyi (avtomat kir yuvish)" },
  { word: "light", translation: "yorug', engil" },
  { word: "living room", translation: "mehmonxona" },
  { word: "market", translation: "bozor" },
  { word: "messy", translation: "tartibsiz" },
  { word: "mine", translation: "meniki" },
  { word: "next to", translation: "yonida" },
  { word: "old", translation: "eski, qari" },
  { word: "old-fashioned", translation: "eski uslubdagi" },
  { word: "on", translation: "ustida" },
];

let currentIndex = 0;

const flashcard = document.getElementById("flashcard");
const nextBtn = document.getElementById("nextBtn");

function updateCard() {
  const front = flashcard.querySelector(".front");
  const back = flashcard.querySelector(".back");
  const currentWord = words[currentIndex];
  front.textContent = currentWord.word;
  back.textContent = currentWord.translation;
}

flashcard.addEventListener("click", () => {
  flashcard.classList.toggle("flipped");
});

nextBtn.addEventListener("click", () => {
  currentIndex = (currentIndex + 1) % words.length;
  flashcard.classList.remove("flipped");
  updateCard();
});

updateCard();
